version: "3.8"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/dev-prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.3.6
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards/:/etc/dashboards/
    ports:
      - 3000:3000
    networks:
      - grafana

  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - grafana

