version: "3.8"

networks:
  grafana:

volumes:
  app_data: {}

services:

  app:
    build: .
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CACHE_DIR=/data/cache
      - ORIGIN=http://origin:5000/
      - JAVA_ARG=-Xlog:gc=debug:file=/data/log/gc.log:time,uptime,level,tags:filecount=5,filesize=100m
      - LOG_REQUESTS=false
    volumes:
      - ./cache/:/data/cache/
      - ./log/:/data/log/
    restart: always
    ports:
      - 8080:8080
    networks:
      - grafana

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  origin:
    build: ./origin_server
    ports: 
      - 5000:5000
    networks:
      - grafana
    environment:
      - TOTAL_IMAGES=10
      - MOUNT_DIR=/data/images/
      - FLASK_APP=main.py
    volumes:
      - ./images/:/data/images/


