version: "3.8"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - app_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--storage.tsdb.retention.size=1GB"
    ports:
      - 9090:9090
    networks:
      - grafana

  app:
    image: orgmanager/image_manager:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CACHE_DIR=/data/cache
      # change it to be more versatile
      - ORIGIN=http://3.125.156.169/
    volumes:
      - app_data:/data/cache
      - /log/:/log/
    ports:
      - 80:8080
    networks:
      - grafana

