spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
image-manager:
  origin-server: http://localhost:5000/
  disk-cache-mount-point: cache
  disk-log-mount-point: log
  url-show-mode: true
logging:
  level:
    org.springframework.web: DEBUG
    web: DEBUG
---
spring:
  datasource:
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: test
image-manager:
  origin-server: http://localhost:5000/
  disk-cache-mount-point: cache
  disk-log-mount-point: log
  url-show-mode: true
---
spring:
  config:
    activate:
      on-profile: prod
image-manager:
  origin-server: ${ORIGIN}
  disk-cache-mount-point: ${CACHE_DIR}
  disk-log-mount-point: ${LOG_DIR}
  url-show-mode: true
---
management:
  healths:
    probles:
      enabled: true
  metrics:
    export.prometheus.enabled: true
    distribution.percentiles.http.server.requests: 0.5, 0.90, 0.99
    web.server.request.autotime.enabled: false
    enable:
      jvm: false
      tomcat: false
      system: false
      logback: false
  endpoints:
    web:
      # by default Spring expose actuator endpoints on /actuator/ path but prometheus needs it be on /
      base-path: /
      exposure:
        include: "*"
      path-mapping:
        # prometheus looks at /metrics by default when scraping for metrics
        metrics: spring-metrics
        prometheus: metrics

