global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "node_exporter"

    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "IO_app"

    static_configs:
      - targets: ["app:8080"]

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: GRAFANA_USERNAME
      password: GRAFANA_PASSWORD
