{
 "title": "image_manager_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Response time (AVG) [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=~\"2..\",uri=\"/{filename}\",})/sum(http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=~\"2..\",uri=\"/{filename}\",})",
     "legendFormat": "AVG_response_time_success [s]"
    },
    {
     "expr": "sum(http_server_requests_seconds_sum{exception=~\".*\",method=\"GET\",outcome=~\".*\",status=~\"[45]..\",uri=\"/{filename}\",})/sum(http_server_requests_seconds_count{exception=~\".*\",method=\"GET\",outcome=~\".*\",status=~\"[45]..\",uri=\"/{filename}\",})",
     "legendFormat": "AVG_response_time_failure [s]"
    }
   ]
  },
  {
   "title": "Response time (MAX) [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=~\"2..\",uri=\"/{filename}\",})",
     "legendFormat": "MAX_response_time_success [s]"
    },
    {
     "expr": "max(http_server_requests_seconds_max{exception=~\".*\",method=\"GET\",outcome=~\".*\",status=~\"[45]..\",uri=\"/{filename}\",})",
     "legendFormat": "MAX_response_time_failure [s]"
    }
   ]
  },
  {
   "title": "Response time (PXX) [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/{filename}\",quantile=\"0.5\",}",
     "legendFormat": "AVG_response_time_success (P50) [s]"
    },
    {
     "expr": "http_server_requests_seconds{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/{filename}\",quantile=\"0.9\",}",
     "legendFormat": "AVG_response_time_success (P90) [s]"
    },
    {
     "expr": "http_server_requests_seconds{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/{filename}\",quantile=\"0.99\",}",
     "legendFormat": "AVG_response_time_success (P99) [s]"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{exception=~\".*\",method=\"GET\",outcome=~\".*\",status=~\"[245]..\",uri=\"/{filename}\",})",
     "legendFormat": "number_of_all_requests"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=~\"[2]..\",uri=\"/{filename}\",})",
     "legendFormat": "number_of_successful_requests"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{exception=~\".*\",method=\"GET\",outcome=~\".*\",status=~\"[45]..\",uri=\"/{filename}\",})",
     "legendFormat": "number_of_failed_requests"
    }
   ]
  },
  {
   "title": "Number of cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_miss_count_total", "legendFormat": "cache_miss_count" }
   ]
  },
  {
   "title": "Inbound traffic [B/s] (measured over the last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(origin_traffic_size_bytes_sum[5m])",
     "legendFormat": "Inbound traffic [B/s]"
    }
   ]
  },
  {
   "title": "Outbound traffic [B/s] (measured over the last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(outbound_traffic_size_bytes_sum[5m])",
     "legendFormat": "Outbound traffic [B/s]"
    }
   ]
  }
 ]
}