{
 "title": "image_manager_profiling",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\", mode!=\"idle\"}[1m]))\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node_exporter:9100\"} - node_memory_Cached_bytes{instance=\"node_exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Used disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\",device!~\"/dev/loop.*\", device!~\"tmpfs|nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node_exporter:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}