version: "3.8"

volumes:
  app_data: {}

services:
  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_ARG=-Xlog:gc=debug:file=/data/log/gc.log:time,uptime,level,tags:filecount=5,filesize=100m
    restart: always
    volumes:
      - ./log/:/data/log/
    ports:
      - 7000:8080