name: Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test


  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOC_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: orgmanager/image_manager:latest
  
  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate prometheus config
      run: |
        sed -e "s/GRAFANA_USERNAME/${{ secrets.GRAFANA_USERNAME }}/;s/GRAFANA_PASSWORD/${{ secrets.GRAFANA_PASSWORD }}/" \
        prometheus/prod-prometheus.yml > prometheus.yml
        
    - name: Copy prometheus config 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu 
        port: 22 
        key: ${{ secrets.DOCKER_PRIVATE_KEY}}
        source: "prometheus.yml,prod-docker-compose.yml,scripts/*,router/*"
        target: "deployment"
        
    - name: Start docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu 
        key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        port: 22 
        script: |
          cd deployment
          chmod +x scripts/*
          ./scripts/deploy.sh