
name: Docker

on:
  push:
    branches:
      - deployment-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate prometheus config
      run: |
        sed -e "s/GRAFANA_USERNAME/${{ secrets.GRAFANA_USERNAME }}/;s/GRAFANA_PASSWORD/${{ secrets.GRAFANA_PASSWORD }}/" \
        prometheus/prod-prometheus.yml > generated-prometheus.yml
        
    - name: Copy prometheus config 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu 
        port: 22 
        key: ${{ secrets.DOCKER_PRIVATE_KEY}}
        source: "generated-prometheus.yml,prod-docker-compose.yml,scripts/deploy.sh"
        target: "deployment"
        
    - name: Start docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu 
        key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        port: 22 
        script: |
          cd deployment
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh